### ISSUE TITLE
Does ApplyMiddleware work with custom StateStreams

### ISSUE THREAD

**Issue by Aleksion** [Aleksion/reduxSwift#10]
I noticed that the subscribe function that's provided to the middlewareApi's is set to the default implementation:

``` swift
            let middlewareApi = Store(
                dispatch: { dispatch($0) },
                subscribe: { _ in SimpleReduxDisposable(disposed: { false }, dispose: {}) },
                getState: store.getState)
```

Previously the middlewareApi didn't have access to the subscribe function - and I don't know whether we need it. 

But I fail to see how that function is actually doing anything atm?

**Comment by agentk** [comment]
The middleware does work with custom StateStreams. I've taken a shortcut when refactoring the MiddlewareApi as it's just a Store without subscribe. So .subscribe() just needed a dummy function for now.

I haven't looked into refactoring the MiddlewareApi again yet. I'll leave this open until I do.
I might create both a Store and MiddlewareApi protocol that the Store conforms to.

**Comment by Aleksion** [comment]
Makes sense. So it is effectively not doing anything but complying to the protocol?

**Comment by agentk** [comment]
Correct. For what it's worth, the builtin SimpleStateStream is a custom StateStream. Anything that works on it should work with other StateStreams too.

**Comment by agentk** [comment]
I've moved MiddlewareApi out to it's own type in 02ade854a56435db461be5a73253376426ad3288.
It's definitely clearer that way. The name change will need to be reflected in any middleware using Store<State>. Feel free to merge it if your happy.

**Comment by agentk** [comment]
So.... MiddlewareApiType was clearly a subset of the StoreType. So I've made that clear in the code by making StoreType a subclass of MiddlewareApiType.

There is no real need to do it. There are only two and three attributes respectively. But it does now establish the formal link.

Tests are passing. I'll merge it into dev for now and mark it for 0.2 release along with removing the StateStream and cleanup.
