### ISSUE TITLE
Async middlewares should travel the whole middleware chain again when store.dispatch is called

### ISSUE THREAD

**Issue by Aleksion** [Aleksion/reduxSwift#2]
Currently a store.dispatch call in a middleware works - it calls the dispatch function AFTER the whole middleware chain is complete. However, it does not travel the middleware chain again. I have to reverse engineer the current ReduxJs implementation and figure out how they do it.

**Comment by sai-prasanna** [comment]
I am yet to try reduxSwift, but I was reading middleware source code in redux js today, so will try to help.Correct me if i misunderstood your problem because I am relatively new to redux..

Are you calling dispatch inside async callbacks?
And is that dispatch the one from middlewareAPI ? If so, why do you expect it to travel through middleware chain, it simply dipatches to store directly without traversing through middleware chain.

I think you should call next(actionObject) in order to call the inner middleware

consider this simple promiseMiddleware

```
export default function promiseMiddleware() {
  return next => action => {
    const { promise, type, ...rest } = action;

    if (!promise) return next(action);

    const SUCCESS = type;
    const REQUEST = type + '_REQUEST';
    const FAILURE = type + '_FAILURE';
    next({ ...rest, type: REQUEST });
    return promise
      .then(res => {
        next({ ...rest, res, type: SUCCESS });

        return true;
      })
      .catch(error => {
        next({ ...rest, error, type: FAILURE });
        console.log(error);
        return false;
      });
   };
}
```

Here you call next with response success or failure action object to pass the action down the middleware chain.

**Comment by Aleksion** [comment]
Hi Sai,

Thx for contributing!
First of all this error has actually already been fixed. I just forgot to update the issue. I forgot to hand over the final dispatch function to the middlewareApi in applyMiddlewares. 

when you return next(action) - you automatically hand it down the middleware chain. 
But in the case of a promise, I would like it to dispatch the promise aciton down the whole middleware chain again, so that any logging etc also gets triggered for that. This should however only happen when you call store.dispatch(action) and not next(action)

The main problem with converting the way the original redux framework handles middlewares to swift is static typing. In javacript you can have the dispatch function return anything -> a promise, an action, an observable. 

I've tried to keep the port as functional as possible - while still utilizing the static nature of swift. So currently the dispatch function returns an action, which makes it hard to enable the flexibility middlewares in redux currently have.

But the main question is, whether you really should interact with the promise further down the middleware chain anyways on the barebone object? If not I think the current implementation is fine - I've show how it can be done in the reduxSwift-rx repo. Using FSA, the payload can be any type you like and you can accomplish this anways. 

But if you have a suggestion to an alternative or/and better way to do it I'm definitely all ears!

Regards

**Comment by sai-prasanna** [comment]
Hi Aleksion,

Thanks for clarifying, I am new to functional programming and JS, and failed to notice that in redux.js the middleware API gets  store.dispatch ~~that uses some kind of functional magic~~  and replaces the function reference to composed dispatch which lets the dispatches to again go through middlewares again .. ~~mind blowing.~~ still awesome

edit:-- 

1.I know this is not proper place to ask, but as you seem to understand this well ,can you clarify whether I am understanding this properly ..

```
export default function applyMiddleware(...middlewares) {
  return (next) => (reducer, initialState) => {
    var store = next(reducer, initialState)
    var dispatch = store.dispatch
    var chain = []

    var middlewareAPI = {
      getState: store.getState,
      dispatch: (action) => dispatch(action)
    }
    chain = middlewares.map(middleware => middleware(middlewareAPI))
    dispatch = compose(...chain)(store.dispatch)

    return {
      ...store,
      dispatch
    }
  }
}
```

Though initially dispatch in middlewareAPI is set to store.dispatch, it gets re assigned to composed dispatch, and hence the dispatch of middlewareAPI points to the composed dispatcher ?? some kind of self referential magic .

2.And great work, by the way, I want to try redux in normal ios applications to have sane knowledge  about states, any recommendation on how to build state, do you store state of all views in store? and persist them on app closing ? And use coredata  or something with a sync/async api built around it and use it to populate states ?

**Comment by Aleksion** [comment]
Well, it's not really magic. If you look at applyMiddleware.js, the store's dispatch function is passed to the middlewareApi - which is basically just a simpler version of store, since it has the original store's getState and dispatch function (this is the first argument that's passed to a middleware)

``` javascript
    var store = next(reducer, initialState)
    var dispatch = store.dispatch /// The store's dispatch function is assigned to the dispatch variable
    var chain = []

 var middlewareAPI = {
      getState: store.getState,
      dispatch: (action) => dispatch(action)
    }
    chain = middlewares.map(middleware => middleware(middlewareAPI))
    dispatch = compose(...chain)(store.dispatch)
```

After that he basically reduces all middlewares dispatch functions and the orginal dispatch function to one new function. He then assigns the value of this to the dispatch variable
 `dispatch = compose(...chain)(store.dispatch)`
And since the variable is updated - and it's passed by reference - the dispatch function of the middlewareAPI is also updated. So whenever store.dispatch is called in a middleware, it will travel the whole middleware chain due to the line I highlighted above.

That's how I've understood it anyways. 
I'm rather new to functional programming as well, so I try to be careful calling it that so I don't offend anyone ;)

**Comment by sai-prasanna** [comment]
Point 1 got addressed before I even posted , thanks :+1:   . btw I will try to contribute

**Comment by Aleksion** [comment]
No problem!
Let me know if you like to test yourself by contributing!
I'm slowly building up surrounding middleware, so this actually becomes a viable alternative to interface builder and storyboards (I have a background in web development, so I hate being dependent on tools like that).
Currently I'm focusing on reduxSwift-router - it's far from done. And I'm using it in two app's I'm developing.
But I could use some help with devTools, Thunk and some of the more fundamental elements of redux.

**Comment by Aleksion** [comment]
I still haven't gotten around to saving the state. But it's built so that you can initiate with an initialState - so that is what you should save - in whatever way suits you best.
If you create an example with coreData, please do share it. I haven't really worked with it so I'd like to see how you structure it.

Regarding creating your appState, there's a small example in the Mocks in the test folder. I prefer creating seperate states for each viewController - so that you don't have to create your whole state tree in a state.swift file. The main appState would then now about each subview like so:

``` swift
struct AppState: State{
 let firstView: FirstViewState!
 let secondView: SecondViewState!
}

struct FirstViewState: State{
   let viewString: String!
}

struct SecondViewState: State{
  let viewString: String!
}
```

This way you can modularize your app. But I haven't factored in how to do the same for persisting the appState. 

Let me know what you think and if you have any suggestions.
