### ISSUE TITLE
Simpler Actions

### ISSUE THREAD

**Issue by lucoceano** [Aleksion/reduxSwift#29]
Hi,

I start using your library, and quickly I starting thinking if Actions shouldn't be a simpler struct, something just with a type, and everything else should be implemented by devs. 

In my case, I'm not using meta or error but my actions always have those fields, should I change the way I'm doing stuff or that makes sense to simplify the Actions?.

Example:

``` swift
public protocol Action {
    var type: String { get }
}

public extension Action {
    public var type: String { return "\(self.dynamicType.self)" }
}
```

**Comment by delebedev** [comment]
+1 here, it was first point of confusion when I was reading the code. Drawing parallels with 'original' redux: action requires type field and that's it. I understand motivation for errors and other meta fields, but would appreciate this discussion rolling

**Comment by agentk** [comment]
I'm really glad you have both raised the question. We had defaulted to using the Flux Standard Action implementation for Actions. 
But it does feel very redundant when declaring a lot of actions. 

I've been thing about making the completely generic, but I might be taking it a bit too far. What about still using the protocol, but dropping the type var declaration seeing as Action is a protocol and has to be conformed to anyway? Actions can still be match on type in a switch statement. Ie

public protocol Action {}

struct MyActionWithoutAPayload: Action {}

We could then change the current Action to FsaAction to retain the same functionality. 

As a side note, I used the error field extensively for promise middleware dealing with API responses to easily log any action that wasn't successful and meta for logging response headers on certain conditions. 

(Excuse the unhughlighted code, I can't work out how to do it on this phone)

**Comment by delebedev** [comment]
Looks like plain `protocol Action {}` is a pretty good _Start_, works well with both enums and structs without any hassle:

``` swift

protocol Action {}

enum MyAppAction: Action {
    case SendMessage(Int)
    case ViewHistory
}


struct MyStruct: Action {
}

func dispatchEnum(action: MyAppAction, state: Int) -> Int {
    switch (action) {
    case .SendMessage(let inc):
        return state + inc
    case .ViewHistory:
        return state + 2
    }
}

func dispatch(action: Action, state: Int) -> Int {
    if let action = action as? MyAppAction {
        return dispatchEnum(action, state: state)
    }

    if action is MyStruct {
        return state + 3
    }

    return 0
}

dispatch(MyAppAction.SendMessage(1), state: 0)

```

**Comment by delebedev** [comment]
One a side note: I really have no idea why people would implement actions as non `enum`: exhaustive switch is so useful :innocent:

**Comment by agentk** [comment]
I like the flexibility of being able to conform and enum! I hadn't thought that as a possibility. 

Then they could still be split into multiple files. The dispatch enum code would probably make a good fit in appropriate reducers.

**Comment by lucoceano** [comment]
I think keep it as simple as possible would be great, and if you yet want to have a more complex struct as base you still can.

**Comment by Aleksion** [comment]
I really like the simplicity AND flexibility of your suggestions. 
That's also right in the spirit of the original framework.
And I really feel that this should be more empowering than restrictive
+1

**Comment by agentk** [comment]
I should be able to create a pull request for this today. I'll give another day for comments before I commit it. 👍

**Comment by agentk** [comment]
Remaining tasks:
- [x] Rename Action to FluxStandardAction
- [x] Create new minimal Action protocol
- [x] Test the new Action
  - [x] enum Action
  - [x] struct Action
  - [x] class Action
- [x] Test the FSA
- [x] Simplify mocks in the tests with the new Action
- [x] Update README
  - Examples:
    - [x] Action
    - [x] FluxStandardAction
- [x] Update docs
- [x] Update playground
