### ISSUE TITLE
Compose function should be able to compose storeEnhancers (applyMiddleware etc).

### ISSUE THREAD

**Issue by Aleksion** [Aleksion/reduxSwift#33]
Currently compose is used in applyMiddleware:

``` Swift

        var dispatch: Dispatch!

        let store = next(reducer, initialState)

        let middlewareApi = MiddlewareApi(
            dispatch: { dispatch($0) },
            getState: store.getState)

        let middlewareChain = middleware.map { $0(middlewareApi) }

        dispatch = compose(middlewareChain)(store.dispatch)

```

For reference:

``` Swift
public typealias Dispatch = Action -> Action
public typealias DispatchTransformer = Dispatch -> Dispatch

```

in this case it composes DispatchTransformers: Dispatch -> Dispatch. So it iterates over each dispatch function and returns its result to the next. Finally it is called with the store's dispatch function - and the dispatch has been enhanced.

However, this doesn't seem to be working with the more complex 

``` Swift
 typealias StoreEnhancer = StoreCreator -> StoreCreator
```

The following: 

``` Swift
let composedStoreEnhancer = compose([applyMiddleware([]), applyMiddleware([])]);
```

Results in:

``` shell
error: cannot convert call result type '(((State?, Action) -> State, State?) -> Store<State>) -> (((State?, Action) -> State, State?) -> Store<State>)' to expected type '_ -> _'
```

I am currently trying to find the root of the error (I suspected it was because It couldn't deduce the generic type - but even with out generics it seems to fail on me).

**Comment by agentk** [comment]
I think you might purely be hitting type issues. The ambiguity is in applyMiddleware where the State type is unknown. Once the StoreEnhancer type is defined in reference to the State, then each step in creating enhancers / composers can be seperate.

``` swift
func loggingMiddleware<State>(store: MiddlewareApi<State>) -> DispatchTransformer {
    return { next in { action in
        print(action)
        return next(action)
        }}
}

typealias Reducer = (AppState?, Action) -> AppState
typealias StoreCreator = (Reducer, AppState?) -> Store<AppState>
typealias 👉StoreEnhancer👈 = StoreCreator -> StoreCreator

let loggingEnhancer: 👉StoreEnhancer👈 = applyMiddleware([loggingMiddleware])
let doubleLoggingEnhancer = compose([loggingEnhancer, loggingEnhancer])
let store = doubleLoggingEnhancer(createStore)(reducer, nil)
```

**Comment by agentk** [comment]
The compose function you wrote is spot on. I can't see anywhere it could do with improvement other than readability and documentation.

**Comment by Aleksion** [comment]
Ha ha, if that's the case I could shoot myself. 
But often times I find that type related issues are really poorly explained by the compiler. 
I'll try it out right away and close the issue accordingly

**Comment by Aleksion** [comment]
Right you are!
But the typealiases seem to be quite important for it to work. Which we should probably include in the documentation.

I'll cook something up.

Good job Karl!
