### ISSUE TITLE
Add CocoaPods support

### ISSUE THREAD

**Issue by waveyus** [Aleksion/reduxSwift#4]
Could you add CocoaPods installation support for those not using Cartfile?  Thanks

**Comment by Aleksion** [comment]
I definitely could - was there a reason you closed the issue?

**Comment by waveyus** [comment]
Thanks. Much appreciated. 
Thought instead of creating an issue here, I can go ahead use Carthage.

But maybe it's good to have both options available for everybody

**Comment by Aleksion** [comment]
I personally prefer Carthage - now that I've gotten used to it. If you're familiar with setting up cocoapods on the projects that you do, you are more than welcome to fork and submit a pull request. I'll reopen the issue and pick it up if you're not up for it :)
