### ISSUE TITLE
Convert depending libraries to the new github target

### ISSUE THREAD

**Issue by Aleksion** [Aleksion/reduxSwift#6]
@agentk - I'm currently wrapping up work before christmas - so I will fix this myself tomorrow evening.
But if you have time to do this before me, please don't hesitate to fix them.

Also regarding the naming - i've but it up as a suggestion. Let me know what you think. Then lets rename all libraries to keep things consistent.

I'll also review and test your pull request tomorrow and merge everything in when I finish my work sprint. 

Once again - welcome aboard @agentk - you've done great work.

**Comment by agentk** [comment]
https://twitter.com/codinghorror/status/506010907021828096

True. Now is also the ideal time to do any renaming. I don't have a good answer. Thinking out loud:

I like the idea of *Kit, ie, MaterialKit, MotionKit, PromiseKit, ReactiveKit.
Or perhaps *.swift, like js libraries, angular.js.
I feels less weird (to my aussie brain) to use Swift as a prefix than a suffix, like SwiftBond, SwiftLint, notable exception where it sounds better as a suffix: RxSwift.
Having Swift/Kit in the org name should make it pretty clear. The org name will also be visible in forks too. I don't think it would be necessary to use Swift in every project name, perhaps just the core project if you decide to.

Choices (alpha sorted):
- Redux
- Redux.swift
- ReduxKit
- ReduxSwift
- reduxSwift
- SwiftRedux

I've asked Siri and she doesn't have a good answer either. I'll let you take lead on this one. Just let me know the format and I can fix them all up. I had my last day of work today. I'll be spending a bit of time simplifying / re-architecting an iOS project with redux over the next couple of weeks.

**Comment by gaearon** [comment]
I think ReduxKit sounds great.

**Comment by Aleksion** [comment]
ReduxKit it is

Thanks a bunch!
