### ISSUE TITLE
Update GitHub pages with new Readme

### ISSUE THREAD

**Issue by agentk** [Aleksion/reduxSwift#7]
Looks like the github pages branch is now broken after all of the moving around. It would also make a good place to drop in a lightly styled version of the readme.

**Comment by agentk** [comment]
Or alternatively use gitbook or cocoadocs?

https://aleksion.gitbooks.io/reduxswift/content/
http://cocoadocs.org/docsets/ReduxKit/

**Comment by Aleksion** [comment]
Hmm. tough one.

I like the presentation style in Gitbook. And it's super easy to write and present the documentation in a pleasing way. It seems great for delivering background, examples and thoughts behind the project - just like in Redux.

However, I really do see the power of having the coocaPods documentation pull out docblocks for all the methods. It makes it super easy to get an overview of what the framework contains.

Should we provide both?

**Comment by agentk** [comment]
Both it is then.

**Comment by agentk** [comment]
The gh-pages branch can now build the gitbook and jazzy docs. They are deployed to http://reduxkit.github.io/ReduxKit/ & http://reduxkit.github.io/ReduxKit/api/ respectively.

The build script pulls in latest master changes and recompiles. Changes can then be checked and pushed to gh-pages.

This no longer requires cocoadocs.org or gitbook.io.

I've cleaned up the jazzy api styling so that it's more mobile friendly now too.

I will need to look at automating the process with travis and a git hook in the future.

@Ben-G / @Aleksion: feel free to reuse as much of the build setup as you want in any project.

Markdown files for the gitbook build go in docs/, and entered into SUMMARY.md.

**Comment by Ben-G** [comment]
Thanks! This setup sounds great!
