### ISSUE TITLE
tvOS and watchOS schemes not building

### ISSUE THREAD

**Issue by agentk** [Aleksion/reduxSwift#9]

**Comment by Aleksion** [comment]
Did you experience the same?
If not I'll start debugging WHY it didn't work on my computer, and document it in here.

**Comment by agentk** [comment]
I've enabled the schemes in https://github.com/ReduxKit/ReduxKit/tree/additional-platform-builds for testing

**Comment by agentk** [comment]
They build without error for me. Does "carthage build --no-skip-current" give you any errors?

**Comment by agentk** [comment]
I'm going to mark this as closed now. I've setup travis for running tests on pushes and attaching carthage release archives to tagged releases in github. Carthage installs will now use the prebuilt binary from github without needing to recompile. Plus codecov.io reports now too.
